changing datatype check to check for integers and not floats
ess-dmsc/nexus-constructor pull request #842
Opened 2021-02-24 09:45 UTC by kmurica

### Issue

https://github.com/ess-dmsc/nexus-constructor/issues/839

### Description of work

Erroneous warning message pops up due to datatype check done for float type rather than integer for vertices.

### Acceptance Criteria 

Test if the erroneous warning message still persists.

2021-02-24 09:57 UTC, kmurica commented
@matthew-d-jones I'm having some issue with my pre-commit here... Not sure why.
It seems to be due to reformatting of _convert_vertices_to_qvector3d

2021-02-24 11:49 UTC, matthew-d-jones commented
@kmurica Probably due to a different version of black in the hook to the requirements file. Try pinning the hook to the same version as in the requirements file, like this: https://github.com/ess-dmsc/forwarder/blob/main/.pre-commit-config.yaml#L3

2021-02-24 13:27 UTC, matthew-d-jones requested changes
I think the correct fix here is to allow integers and floats.
Users are allowed to enter a non-integer position in the interface. I think the problem occurs when a user chooses a value that happens to be an integer so when the float is saved to JSON and then loaded back, python converts the string to an integer.
`float -> str -> int` rather than `float -> str -> float`

The list is cast to a qvector3d after this point in the code, I assume that works fine from integer or float. If not then you would need to explicitly cast to float first.

2021-02-25 07:44 UTC, matthew-d-jones approved these changes
Thanks. Manually tested and works as expected.

2021-02-25 07:44 UTC, merged